### PR TITLE
Fix some comparisons with members and functions, avoid taking private member/function

### PR DESCRIPTION
**Pull request by davidwalter2**

### CODE REVIEW

**Comment by kdlong** [comment]
I think the last commit is the one you want to add, right? I can cherry pick it and commit just that. I went around in circles with storage_type and storage_type(), not surprised I messed it up. I guess there were some differences where storage_type is compared to Weight() and it fails the comparison incorrectly? 

As for _storage_type vs. storage_type, I think this is just a question of how you access the attribute, I didn't actually realise h.storage_type worked, I think we previously used h._storage_type for whatever reason. Maybe @bendavid had one, or maybe it was just an oversight.

**Comment by davidwalter2** [comment]
Right, there are some commits from main that are probably not in this branch but it is the last one that I wanted to make the PR for, so yes I think you can cherry pick. 

Yes there were some comparison between storage_type and Weight() which gives always false. 

Since there exists h.storage_type I thought it is a better choice than h._storage_type by may be there is a reason for the other

**Comment by bendavid** [comment]
For _storage_type vs storage_type there was actually an API change on the hist and/or boost_histogram side at some point, and one of these is deprecated.

**Comment by davidwalter2** [comment]
I found this in boost_histogram:
https://github.com/scikit-hep/boost-histogram/blob/2d0e184b8e48722c69da49c6d4b3e1f3c1eaa79a/src/boost_histogram/_internal/hist.py#L597

and this in hist
https://github.com/scikit-hep/hist/blob/a4746c7aec1238c8fdc1206d00c5dd822fc69c33/src/hist/basehist.py#L123-L128

for me it seems _storage_type is the deprecated one

**Comment by kdlong** [comment]
I cherry picked this single commit

**Pull request closed without merging**
